name: Monday AI Event Digest
on:
  schedule:
    - cron: '30 12 * * 1'  # Every Monday 6:00 PM IST (12:30 UTC)
  workflow_dispatch:  # Manual trigger for testing

jobs:
  send-monday-digest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          pip install requests python-dotenv
      
      - name: Send Monday AI Event Digest
        env:
          EVENTBRITE_TOKEN: ${{ secrets.EVENTBRITE_TOKEN }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: python Ai-event_notifier.py

      - name: Log completion
        run: echo "Monday digest sent successfully at $(date)"
