name: Monday AI Event Digest
on:
  schedule:
    - cron: '30 12 * * 1'  # Every Monday 6:00 PM IST (12:30 UTC)
  workflow_dispatch:  # Manual trigger for testing

jobs:
  send-monday-digest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev
      
      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir requests python-dotenv
      
      - name: Verify Python installation
        run: |
          python -c "from email.mime.text import MimeText; print('Email module working')"
          python -c "import smtplib; print('SMTP module working')"
      
      - name: Send Monday AI Event Digest
        env:
          EVENTBRITE_TOKEN: ${{ secrets.EVENTBRITE_TOKEN }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: python Ai-event_notifier.py

      - name: Log completion
        run: echo "Monday digest sent successfully at $(date)"
