name: Monday AI Event Digest
on:
  schedule:
    - cron: '30 12 * * 1'
  workflow_dispatch:

jobs:
  send-monday-digest:
    runs-on: windows-latest  # Try Windows instead of Ubuntu
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv
      
      - name: Test email imports
        run: |
          python -c "from email.mime.text import MIMEText; print('MIMEText working')"
          python -c "from email.mime.multipart import MIMEMultipart; print('MIMEMultipart working')"
      
      - name: Send Monday AI Event Digest
        env:
          EVENTBRITE_TOKEN: ${{ secrets.EVENTBRITE_TOKEN }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: python Ai-event_notifier.py
