name: Monday AI Event Digest
on:
  schedule:
    - cron: '30 12 * * 1'  # Every Monday 6:00 PM IST (12:30 UTC)
  workflow_dispatch:  # Manual trigger for testing

jobs:
  send-monday-digest:
    runs-on: ubuntu-22.04  # Try different Ubuntu version
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'  # Specific stable version
      
      - name: Force reinstall Python email modules
        run: |
          python -m pip install --upgrade pip
          python -c "import sys; print(f'Python version: {sys.version}')"
          python -c "import email; print(f'Email module path: {email.__file__}')"
      
      - name: Test email imports with debugging
        run: |
          python -c "
          import sys
          import os
          print('Python executable:', sys.executable)
          print('Python path:', sys.path[0])
          
          # Try to import and show what's available
          import email.mime.text as emt
          print('Available in email.mime.text:', dir(emt))
          
          try:
              from email.mime.text import MIMEText
              print('SUCCESS: MIMEText imported')
          except ImportError as e:
              print('IMPORT ERROR:', e)
              # Show the actual file contents
              print('Module file:', emt.__file__)
          "
      
      - name: Install dependencies
        run: pip install requests python-dotenv
      
      - name: Send Monday AI Event Digest
        env:
          EVENTBRITE_TOKEN: ${{ secrets.EVENTBRITE_TOKEN }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: python Ai-event_notifier.py
